version: "3.3"
services:
  nginx:
    restart: unless-stopped
    image: nginx:1.20.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /var/www/nikolaydemidovez.by:/var/www/nikolaydemidovez.by
      - /var/www/admin.nikolaydemidovez.by:/var/www/admin.nikolaydemidovez.by
      - /var/www/club.nikolaydemidovez.by:/var/www/club.nikolaydemidovez.by
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
